lr: 1e-5
init_epoch: 0
epochs: 5
test_epoch: 50
restore: false
gpu_id: 0
is_debug: no
feat_dim: 2883
name: 'coarse_mvp2m'
save_path: '/home/giga/Desktop/davistao/p2m_tf2/Pixel2Mesh-Tensorflow2/results'

# train
train_file_path: 'data/train_list.txt'
train_data_path: '/home/giga/Desktop/davistao/p2m_tf2/Pixel2Mesh-Tensorflow2/data/ShapeNetModels/p2mppdata/train'
train_image_path: '/home/giga/Desktop/davistao/p2m_tf2/Pixel2Mesh-Tensorflow2/data/ShapeNetImages/ShapeNetRendering'
# test
test_file_path: 'data/test_list.txt'
test_data_path: '/home/giga/Desktop/davistao/p2m_tf2/Pixel2Mesh-Tensorflow2/data/ShapeNetModels/p2mppdata/test'
test_image_path: '/home/giga/Desktop/davistao/p2m_tf2/Pixel2Mesh-Tensorflow2/data/ShapeNetImages/ShapeNetRendering'
# coarse result
coarse_result_file_path: 'data/train_list.txt'
coarse_result_data_path: '/home/giga/Desktop/davistao/p2m_tf2/Pixel2Mesh-Tensorflow2/data/ShapeNetModels/p2mppdata/train'
coarse_result_image_path: '/home/giga/Desktop/davistao/p2m_tf2/Pixel2Mesh-Tensorflow2/data/ShapeNetImages/ShapeNetRendering'


