# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streaming.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstreaming.proto\x12\tstreaming\" \n\rClientMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"\xa9\x01\n\rServerMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x15\n\rimg_feat_json\x18\x02 \x01(\t\x12\x0f\n\x07number1\x18\x03 \x01(\x05\x12\x0f\n\x07number2\x18\x04 \x01(\x05\x12\x0e\n\x06p_loss\x18\x05 \x01(\x05\x12\x0e\n\x06\x65_loss\x18\x06 \x01(\x05\x12\x0e\n\x06n_loss\x18\x07 \x01(\x05\x12\x0e\n\x06l_loss\x18\x08 \x01(\x05\x12\x0e\n\x06m_loss\x18\t \x01(\x05\x32\x61\n\x10StreamingService\x12M\n\x13\x42idirectionalStream\x12\x18.streaming.ClientMessage\x1a\x18.streaming.ServerMessage(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streaming_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIENTMESSAGE._serialized_start=30
  _CLIENTMESSAGE._serialized_end=62
  _SERVERMESSAGE._serialized_start=65
  _SERVERMESSAGE._serialized_end=234
  _STREAMINGSERVICE._serialized_start=236
  _STREAMINGSERVICE._serialized_end=333
# @@protoc_insertion_point(module_scope)
